### ISSUE TITLE
[Umbrella] Bugs

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#201]
- [x] Navigation card is broken

- [x] Change scan answer box to be `<pre>`

- [x] Required Thrusters don't change

- [x] Make it obvious on core when crew has transported something 

- [x] Something is wrong with the shields, making them not responsive. Find out what it is and fix it 

- [x] Short Range Comm Core has layout issues. Can't close last comm 

- [x] Power distribution sometimes flakes when dragging bars 

- [x] Make damage report card field use `<pre>` 

- [x] Use system display name in reactivation code notification 

- [x] ~~Tractor beam Strength needs to be tied to power~~ - Making it's own issue

- [x] "New Security Team" placeholder on the damage teams card 

- [x] Processed data from sensors showed up on Probe Network 

- [x] Probe network probes show up in probe control list - shouldn't 

- [x] Internal sensors super broken 

- [x] Sensors resets movement when check 'Ask for speed'

**Comment by isaacOstler** [comment]
Why add the <pre> tag to scan answers?  Some people may see HTML support as a feature instead of a bug! ... granted you could also pass javaScript which could be dangerous ...  Sanitize <script> tags?

**Comment by alexanderson1993** [comment]
It's the answer box. It needs to have some CSS styles added so that returns are rendered properly. https://www.w3schools.com/tags/tag_pre.asp

**Comment by isaacOstler** [comment]
couldn't you just replace \n with <br /> ?

**Comment by Inventicon** [comment]
What is wrong with using <pre>

**Comment by alexanderson1993** [comment]
I would prefer to use CSS instead of doing a string replacement.

**Comment by isaacOstler** [comment]
Either way works, the only downside to using `<pre>` means you'll lose HTML support.  For example, say I wanted the "WARNING" in my message to be red, I could type `<span style='color:red'>WARNING</span> `blah blah blah to achieve this.  Using pre will remove this functionality.   Bug or feature, you decide!

Last time I used `<pre>` it also had problems with some CSS properties...  I could be wrong about that though.

**Comment by Inventicon** [comment]
Good point. Interesting thought: WYSIWYG support for sensor scans.

**Comment by alexanderson1993** [comment]
Somebody else can implement it. I'm not going to.
