### ISSUE TITLE
Umbrella - Bugs

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#214]
- [x] Everything broke when breaking a specific system
- [x] Coolant doesn't update on the coolant card when it changes on other cards
- [x] Default to having some torpedos
- [x] Tactical targeting lock on wasn't working properly - *Unable to reproduce*
- [x] Probe construction doesn't have good scrolling support
- [x] The click area to switch cards is too wide with long card names, like Probe Construction.
- [x] LRM on Core has a tiny font size
- [x] Core layouts was super busted
- [x] Create a feature where a station is automatically logged in. Good for engineering stations
- [x] When configuring a system, make it so the required power actually works.
- [x] Sensors pings actively when it is on manual setting
- [x] Clarify the labels on Probe Construction
- [x] Tractor Beam Strength bar jumps away from the mouse
- [x] Adjust what shows up on the stealth field. Make it look better, 
- [x] One sensor contact showed up with a missing image
- [x] Fix the subscription so newly created flights show up on the Welcome screen
- [x] When setting up clients on sets, show which stations have already been assigned
- [x] Make it so the client list has a scroll bar
- [x] Rooms didn't show up on Security Teams, Tranzine, Damage Teams, etc.
- [x] Unclear how to 'Send' a security team. Add a send button.
- [x] Make it easier to know which client is which. Change from UUID to a 3 word name
- [x] Make the calculator have bigger numbers
- [x] Deck order on security scans is off
- [x] Scanning internally did not update
- [x] When creating a security team, if you delete the name, put a place holder in place of nothing
- [x] Expand the orders box dynamically as you type in it
- [x] Transporters was broken. Need to figure out why
- [x] Make an animation for LRM for message sending (make the dot bigger)
- [x] Internal Comm not working
- [x] LRMs not showing up until a reload of the page occurs
- [x] Make it so the Settings Ball buttons do something
- [x] Adjusting Yaw on core is funky
- [x] Power distribution Battery should be one card
- [x] Remove 'Login', 'Offline', and 'Viewscreen' from the card dropdown
- [x] Alphabetize the list of cards/cores in config. When adding a card, prepopulate the name field with the component name
- [x] Names that are long go outside of the card name box
- [x] If I click on the words on shield control, it makes the fore frequency flicker
- [x] When clients first connect, they don't have an ID, and so they don't show up in the client list
- [x] Add step button on mission config gets squished
- [x] Test with a full build

**Errors**
- [x] Missing Systems in 'Reactors'
- [x] Comm signals - Make it work with no signals
- [ ] Security Scans _scanRequest cannot read name property
- [ ] Cannot read 0 of undefined - SecurityScans componentWillRecieveProps
- [x] Unmounded Sensor SetState
- [ ] Cannot read location - GridDom
- [x] Map Key - Probe Equipment
- [x] Map Key - Coolant Control
- [x] Read only property speed on Engine Control
- [x] SetState called on Unmounted Navigation
- [x] SetState called on Unmounted StealthField
- [ ] Cannot read ID on ClientView - ComponentWillRecieveProps
- [x] Cannot read URL of undefined - assets.js:67
