### ISSUE TITLE
Umbrella - More Bugs

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#223]
- [x] Thrusters can have both 0˚ and 360˚
- [x] Weapons has a limit to the targets it can take. Refactor the animation system
- [x] Dragging power distribution has different mouse offset
- [x] Tractor beam strength dragger is broken
- [x] When dragging comm line on SRComm, it doesn't follow the mouse well
- [x] Widgets dont’ show up - probably FontAwesome
- [x] Overflow scroll on damage team card
- [x] Default target picture not showing up on the targeting screen - Have to test on two computers
- [x] When power is set to 0, you can’t change it on the systems core
- [x] Security Teams don’t disappear if they are selected
- [x] Reactivation code notification didn’t say words
- [x] Strange things going on with the alert condition and the name of the simulator
- [x] Recurring processes are kinda weird. Like, they don’t even run properly. Not sure why.
- [x] Filling coolant on engineering doesn’t change coolant on engine control
- [x] On 4 shield configs, shields are not lined up the right way
- [x] Make the comm arrows have white outlines so they are more easily seen
- [x] The login name can exceed the length of the orange box if it is too long
- [x] When connected to a frequency on SRComm, make the side sine waves a different color or animate
- [x] Create security decks core control
- [x] You can still transfer coolant, even if a system/reservoir is full
- [x] Tractor beam is never stealthy
- [x] Add random station under the actions core widget, to flash a random station, for example
- [x] Probes don't do anything after you click them (???)
- [x] Font Awesome is not loading on built server
- [x] The army contact icon is missing
- [x] Coordinates were not sent to Navigation After 'Random - Send'
- [x] "Cannot read prop 'name' of undefined" on security scans - made it so the button didn't work
- [x] Add heat to engine control
- [x] Show sensors ping on core
- [x] Offline all stations
- [x] Add default torpedo counts
- [x] Use colors with boldness on Damage Reports card
- [x] It took a second for a message to appear on LR Decoding
- [x] Reactivation code accepted sent blank notifications to all stations
- [x] Alphabetize Deck and room list on internal comm
- [x] Alert condition broken?
