### ISSUE TITLE
[Umbrella] Bugs

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#261]
- [x] Dropdown menus for decks and rooms don't scroll

- [x] Ensure there is verbal comm between crew. Consider removing LR comm from all stations

- [x] Make it easier to see how thruster knobs work

- [x] Additional Damage systems on IIFX, like brigs, water pipes, etc.

- [x] Make crew core obvious

- [x] LRM on IIFX

- [x] Messaing on IIFX

- [x] Not enough frequency range to decode message on decoding

- [x] Be able to message from specific damage and security teams

- [x] Notifications for incoming messages

- [x] Make instructions for targeting ships

- [x] Limit how much clicking on buttons sends messages. Batch them or something

- [x] Messaging not showing up on security screen

- [x] Total power used on systems core

- [x] Torpedo loading didn't show up on built version

- [x] Cards are too sparse. Make it so hidden content shows all the time

- [x] Damage teams were not being sent

- [x] Command substr error for some reason

- [x] #Deck and #Number in damage reports wasn't being translated. Same with rooms. Also, should be consistent for the entire report

- [x] Command status picture didn't show up
- [x] Takes time for alert condition to switch
- [x] Bigger widget icons
- [x] Flight thought ship in middle of thrusters was sensors
